export { default as DataTable }      from "./DataTable.vue"
export { default as TableHead }      from "./Components/TableHead.vue"
export { default as TableBody }      from "./Components/TableBody.vue"
export { default as Pagination }     from "./Components/Pagination.vue"
export { default as PaginationLink } from "./Components/PaginationLink.vue"
